// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAizTpZGBo_9QULLT1h7Zmpak7XChfMBlY',
    appId: '1:845830221042:web:b978141afe290b793e346b',
    messagingSenderId: '845830221042',
    projectId: 'exam-advanseflutter',
    authDomain: 'exam-advanseflutter.firebaseapp.com',
    storageBucket: 'exam-advanseflutter.appspot.com',
    measurementId: 'G-32CC116VMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYnrBvHg8ivMnNRCB4RvoRKO-6zcQzpVw',
    appId: '1:845830221042:android:b3d0d40bbb829e643e346b',
    messagingSenderId: '845830221042',
    projectId: 'exam-advanseflutter',
    storageBucket: 'exam-advanseflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkdVJc-SluQ4iS52nUrLFZI4HzwxD7_ys',
    appId: '1:845830221042:ios:354e69c0ee0b678e3e346b',
    messagingSenderId: '845830221042',
    projectId: 'exam-advanseflutter',
    storageBucket: 'exam-advanseflutter.appspot.com',
    iosBundleId: 'com.example.finalExamAdvanceFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkdVJc-SluQ4iS52nUrLFZI4HzwxD7_ys',
    appId: '1:845830221042:ios:354e69c0ee0b678e3e346b',
    messagingSenderId: '845830221042',
    projectId: 'exam-advanseflutter',
    storageBucket: 'exam-advanseflutter.appspot.com',
    iosBundleId: 'com.example.finalExamAdvanceFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAizTpZGBo_9QULLT1h7Zmpak7XChfMBlY',
    appId: '1:845830221042:web:0bfcad575f3d09fb3e346b',
    messagingSenderId: '845830221042',
    projectId: 'exam-advanseflutter',
    authDomain: 'exam-advanseflutter.firebaseapp.com',
    storageBucket: 'exam-advanseflutter.appspot.com',
    measurementId: 'G-F8LKB10E16',
  );
}
